### ISSUE TITLE
Proposal for adding macro that combine pluck and toArray methods

### ISSUE THREAD

**Issue by sushchyk** [spatie/laravel-collection-macros#109]
When you are working with Laravel, especially with Eloquent, you often need to use [`pluck` ](https://laravel.com/docs/5.5/collections#method-pluck) and [`toArray`](https://laravel.com/docs/5.5/collections#method-toarray)methods together:
`$event->users()->sync($users->pluck('id')->toArray()) `

With simple `pluckToArray` macro (I think, macro might be called shorter) it can be written as:
`$event->users()->sync($users->pluckToArray('id'))`

This macro also can be useful when using it with other methods for models, relationships and builder like [`attach`](https://laravel.com/docs/5.5/eloquent-relationships#many-to-many), [`toggle`](https://laravel.com/docs/5.5/eloquent-relationships#many-to-many), [`find`](https://laravel.com/docs/5.5/eloquent#retrieving-single-models), [`destroy`](https://laravel.com/docs/5.5/eloquent#deleting-models), [`whereIn`](https://laravel.com/docs/5.5/queries#where-clauses) and need to pass  attributes from collections as array to them. I thought it might be added to this repository after I saw [`filterMap`](https://github.com/spatie/laravel-collection-macros#filtermap), because it is resolves very similar issue.

I just realized that it is not pure enough, because all methods except `all` and `toArray` return Collection/scalar/object, but on practice people most often use `toArray` just because of using `pluck`, so I think way to get array of attributes by single method should exists.  This makes it easier to work with collections in some cases.

**Comment by freekmurze** [comment]
I'm ok with adding `pluckToArray`, send a PR with tests.

**Comment by sebastiandedeyne** [comment]
`sync` allows collections in recent Laravel versions. Tbh I think it makes more sense to make Laravel PR's that allow collections everywhere (I've done them in the past and they generally get accepted) than adding this workaround, which saves a mere 2 characters.
