### ISSUE TITLE
Shouldn't parallelMap return a new collection?

### ISSUE THREAD

**Issue by JosephSilber** [spatie/laravel-collection-macros#110]
Instead of this:

https://github.com/spatie/laravel-collection-macros/blob/9574b4160b842e79e8ade620e93cc0d5c6e7a242/src/macros/parallelMap.php#L31-L33

...shouldn't we return a new collection, like a regular `map` does?

```php
return new static(wait($promises));
```

I understand that this is a breaking change, and probably wouldn't happen anytime soon. Wondering why it isn't this way currently.

**Comment by sebastiandedeyne** [comment]
Hmm I consider this a bugfix instead of a breaking change

**Comment by freekmurze** [comment]
Yeah, let's consider it a bugfix. I'll take care of it soon.
