### ISSUE TITLE
Laravel 5.4.36 install fails

### ISSUE THREAD

**Issue by peterRd** [spatie/laravel-collection-macros#120]
Installation via composer fails for this version of laravel when using v2 and master. v1 works but doesn't have the parallel map. 

> Your requirements could not be resolved to an installable set of packages.
> Problem 1
>     - Installation request for spatie/laravel-collection-macros v2 -> satisfiable by spatie/laravel-collection-macros[2.0.0].
>     - Conclusion: remove laravel/framework v5.4.36
>     - Conclusion: don't install laravel/framework v5.4.36
>     - spatie/laravel-collection-macros 2.0.0 requires illuminate/validation ~5.2.0|~5.3.0 -> satisfiable by illuminate/validation[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
>     - don't install illuminate/validation v5.2.0|don't install laravel/framework v5.4.36
>     - don't install illuminate/validation v5.2.19|don't install laravel/framework v5.4.36
>     - don't install illuminate/validation v5.2.21|don't install laravel/framework v5.4.36
>     - don't install illuminate/validation v5.2.24|don't install laravel/framework v5.4.36
>     - don't install illuminate/validation v5.2.25|don't install laravel/framework v5.4.36
>     - don't install illuminate/validation v5.2.26|don't install laravel/framework v5.4.36
>     - don't install illuminate/validation v5.2.27|don't install laravel/framework v5.4.36
>     - don't install illuminate/validation v5.2.28|don't install laravel/framework v5.4.36
>     - don't install illuminate/validation v5.2.31|don't install laravel/framework v5.4.36
>     - don't install illuminate/validation v5.2.32|don't install laravel/framework v5.4.36
>     - don't install illuminate/validation v5.2.37|don't install laravel/framework v5.4.36
>     - don't install illuminate/validation v5.2.43|don't install laravel/framework v5.4.36
>     - don't install illuminate/validation v5.2.45|don't install laravel/framework v5.4.36
>     - don't install illuminate/validation v5.2.6|don't install laravel/framework v5.4.36
>     - don't install illuminate/validation v5.2.7|don't install laravel/framework v5.4.36
>     - don't install illuminate/validation v5.3.0|don't install laravel/framework v5.4.36
>     - don't install illuminate/validation v5.3.16|don't install laravel/framework v5.4.36
>     - don't install illuminate/validation v5.3.23|don't install laravel/framework v5.4.36
>     - don't install illuminate/validation v5.3.4|don't install laravel/framework v5.4.36
>     - Installation request for laravel/framework (locked at v5.4.36, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.36].
> 

The project is locked to have 5.4.36

**Comment by freekmurze** [comment]
We don’t maintain v1 anymore.

**Comment by peterRd** [comment]
Thanks for that. Correct me if i'm wrong but shouldn't the ReadMe be updated then?

> This version is targeted at Laravel 5.5. & 5.6 For Laravel 5.2 or 5.3, take a look at the v1 branch. For 5.4 the v2 branch.

Based on the composer output v1 is for 5.4 and v2 is for 5.2/5.3
