### ISSUE TITLE
FirstOrFail

### ISSUE THREAD

**Issue by gizburdt** [spatie/laravel-collection-macros#124]
Hi,

I created the FirstOrFail macro myself a while ago, with a PR. But looking at it now, I'm wondering if the macro needs changes: https://github.com/spatie/laravel-collection-macros/blob/master/src/macros/firstOrFail.php#L12-L14.

Now, the FirstOrFail macro returns a new collection when finding a first element. Isn't is more logical to actually return the first item, when it's present?

If you agree, I can create a new PR :)

**Comment by freekmurze** [comment]
I agree, create a PR with tests and an updated readme. Thanks!
