### ISSUE TITLE
Split throws an error when collection is empty

### ISSUE THREAD

**Issue by jstoone** [spatie/laravel-collection-macros#13]
When using chunk for splitting a collection into groups, the `$groupSize` has to be greater than 0, or else chunk will throw an error.

So when using the following calculation `ceil($this->count() / $numberOfGroups)`, if the collection is empty, `$this->count()` returns 0 and`chunk()` will throw an error.

In my own projects I've been doing the following to handle empty collections in blade instead:
```blade
<?php
    $groupSize = 4;
?>
<div class="row">
@foreach(range(1,$groupSize) as $index)
    <div class="col-md-3">

    @foreach($user->posts->forPage($index, $groupSize) as $user)
        <h1>{{$user->name}}</h1>
    @endforeach

    </div>
@endforeach
</div>
```

So before I make a pull-request for handling the zero value, I'd like to know whether this is the intended behavior, to mimic the `chunk()`, or if it would make sense to just return the collection itself?
If following `chunk()` is the plan, I think an exception should get called with another message, since the user would be scratching their heads, looking for a call to `array_chunk`.

So as a recap, I have two solutions in mind:
1. Make an early return of `$this`, if the `count() == 0`
2. Throw a custom exception: _"split(): Size parameter expected to be greater than 0"_

**Comment by sebastiandedeyne** [comment]
An early return sounds the way to go 👍 

Otherwise it would be really annoying to have to do en empty check every time `split` is called.
