### ISSUE TITLE
Prioritize macro resets keys

### ISSUE THREAD

**Issue by mikemand** [spatie/laravel-collection-macros#152]
When using a collection that is keyed, if you use the prioritize macro it resets the keys. For example:

```php
$original = collect([
    [
        'mfr' => 'Apple',
        'name' => 'iPhone Xs',
    ],
    [
        'mfr' => 'Google',
        'name' => 'Pixel 3',
    ],
    [
        'mfr' => 'Microsoft',
        'name' => 'Lumia 950',
    ],
    [
        'mfr' => 'OnePlus',
        'name' => '6T',
    ],
    [
        'mfr' => 'Samsung',
        'name' => 'Galaxy S9',
    ],
]);

dump($original);

$keyed = $original->keyBy('mfr');

dump($keyed);

$prioritized = $keyed->prioritize(function ($phones, $mfr) {
    return \in_array($mfr, ['OnePlus', 'Samsung']);
});

dump($prioritized);
```

Here's the output:
<img width="447" alt="screen shot 2019-01-23 at 3 41 54 pm" src="https://user-images.githubusercontent.com/745184/51642137-7d6c2080-1f25-11e9-9895-dc00805b900b.png">

**Comment by freekmurze** [comment]
Changing this now would be a breaking change. I'll consider fixing this when releasing a new major version. Feel free to already send a PR that fixes this.
