### ISSUE TITLE
Autocomplete in IDE's for custom macros?

### ISSUE THREAD

**Issue by jonnywilliamson** [spatie/laravel-collection-macros#16]
Hi there, 

This is a great collection. I love it!

I was however wondering if there was anyway we could get autocomplete working for phpstorm (or other IDEs) for these added custom macros?

At the moment when I try and use one (say `mapToAssoc`), my IDE lets me know it doesn't recognise that method:

![image](https://cloud.githubusercontent.com/assets/2513663/18615612/ea1bcd7e-7da2-11e6-9ee0-50a2fbb50a77.png)

One `solution` is to add a `@method` docblock on the main `Illuminate\Support\Collection` class like this:
![image](https://cloud.githubusercontent.com/assets/2513663/18615617/0a1ba680-7da3-11e6-9c81-108f1cd4509b.png)

This works well, and my IDE is instantly happy:

![image](https://cloud.githubusercontent.com/assets/2513663/18615619/2246df90-7da3-11e6-8454-4f5a575dc40a.png)

However this is permanent or practicable solution because that file will get overwritten as the framework gets updated.

Does anyone else have any clever ideas of where I could add this docblock or some other way around this? It would be much appreciated!

Oh, and no, I have not sent a postcard yet. I will rectify that soon. :flushed:

**Comment by jonnywilliamson** [comment]
I had a look at Barry IDE package, and one reply in a topic caught my eye:

https://github.com/barryvdh/laravel-ide-helper/issues/40#issuecomment-58479883

However I have not been able to make this work either, or I'm "doing it wrong"

**Comment by freekmurze** [comment]
It would be handy if there was IDE completion for macro's. However I feel that this problem cannot be solved within this package.

If you have a suggestion on how our code could be altered to support IDE completion, reopen this issue.

**Comment by cotcotquedec** [comment]
You can solve it by declaring a file like ide helper 
work for me with Phpstorm

For the macro 
```php
 // Ajout du count
        Builder::macro('addSelectCount', function($column, $alias = null) {

            $raw = sprintf('COUNT(%s)', $column);

            if (!is_null($alias)) {
                $raw .= ' as ' . $alias;
            }

            $this->selectRaw($raw);
        });

        // Ajout du de la somme
        Builder::macro('addSelectSum', function($column, $alias = null) {

            $raw = sprintf('SUM(%s)', $column);

            if (!is_null($alias)) {
                $raw .= ' as ' . $alias;
            }

            $this->selectRaw($raw);
        });
```



```php
<?php
/**
 * Ce fichier a pour but d'aider à l'autocompletion dans PhpStorm,
 *
 * Il rajoute Les macro et autre function qui ne sont pas active via l'autocompletion
 */

namespace  {
    exit("This file should not be included, only analyzed by your IDE");
}


namespace Illuminate\Database\Query {

    /**
     * Class Builder
     * @package Illuminate\Database\Query
     */
    class Builder
    {

        /**
         * Ajoute une colonne : SUM($columns) as $alias
         *
         * @param $column
         * @param null $alias
         * @return $this
         */
        public function addSelectSum($column, $alias = null) {
            return $this;
        }


        /**
         * Ajoute une colonne : COUNT($columns) as $alias
         *
         * @param $column
         * @param null $alias
         * @return $this
         */
        public function addSelectCount($column, $alias = null) {
            return $this;
        }
    }
}
```

**Comment by jonnywilliamson** [comment]
Hi @cotcotquedec 

Yeah I should have added what my solution was here as well only I forgot!

I created a file in `resources\IDEHelp\IDEAutocomplete.php` so that it would get indexed by PHPStorm.

In that file I have the following which I can update when needed:

```php
<?php
namespace Illuminate\Support;

/**
 * @method dd() Dump the contents of the collection and terminate the script.
 * @method dump() Dump the arguments given followed by the collection.
 * @method Collection ifEmpty(callable $callback) Execute a callable if the collection is empty, then return the collection.
 * @method Collection ifAny(callable $callback) Execute a callable if the collection isn't empty, then return the collection.
 * @method Collection range($start, $end, $step) Create a new collection instance with a range of numbers. `range` accepts the same parameters as PHP's standard `range` function.
 * @method bool none($key, $value) Check whether a collection doesn't contain any occurrences of a given item, key-value pair, or passing truth test. `none` accepts the same parameters as the `contains` collection method.
 * @method bool validate(callable $callback) Returns true if $callback returns true for every item. If $callback is a string or an array, regard it as a validation rule.
 * @method Collection groupByModel(callable $callback, $keyName) Group a collection by an Eloquent model.
form collection item, allowing you to pass a callback to customize its key and value through a map operation.
 * @method Collection transpose() Transpose an array.
 * @method mixed then(callable $callback) Pass the collection to the given callback and return the result.
 */
class Collection
{
}
```

This does exactly what I need.

Does your solution offer any advantages?

**Comment by akalongman** [comment]
One disadvantage of your workaround is an IDE notice "Other declaration of class "ClassName" exists at Classname.php"

**Comment by greaterking** [comment]
How does one get this to play nice with magic methods. `Collection::SomeMarcro()` and `collect()->SomeMacro()`?

**Comment by zotopteam** [comment]
> You can solve it by declaring a file like ide helper work for me with Phpstorm
> 
> For the macro
> 
> ```
>  // Ajout du count
>         Builder::macro('addSelectCount', function($column, $alias = null) {
> 
>             $raw = sprintf('COUNT(%s)', $column);
> 
>             if (!is_null($alias)) {
>                 $raw .= ' as ' . $alias;
>             }
> 
>             $this->selectRaw($raw);
>         });
> 
>         // Ajout du de la somme
>         Builder::macro('addSelectSum', function($column, $alias = null) {
> 
>             $raw = sprintf('SUM(%s)', $column);
> 
>             if (!is_null($alias)) {
>                 $raw .= ' as ' . $alias;
>             }
> 
>             $this->selectRaw($raw);
>         });
> ```
> 
> ```
> <?php
> /**
>  * Ce fichier a pour but d'aider à l'autocompletion dans PhpStorm,
>  *
>  * Il rajoute Les macro et autre function qui ne sont pas active via l'autocompletion
>  */
> 
> namespace  {
>     exit("This file should not be included, only analyzed by your IDE");
> }
> 
> 
> namespace Illuminate\Database\Query {
> 
>     /**
>      * Class Builder
>      * @package Illuminate\Database\Query
>      */
>     class Builder
>     {
> 
>         /**
>          * Ajoute une colonne : SUM($columns) as $alias
>          *
>          * @param $column
>          * @param null $alias
>          * @return $this
>          */
>         public function addSelectSum($column, $alias = null) {
>             return $this;
>         }
> 
> 
>         /**
>          * Ajoute une colonne : COUNT($columns) as $alias
>          *
>          * @param $column
>          * @param null $alias
>          * @return $this
>          */
>         public function addSelectCount($column, $alias = null) {
>             return $this;
>         }
>     }
> }
> ```

when i use like this, my phpstorm show this:

Expression result is not used anywhere
