### ISSUE TITLE
_x_WithRemaining

### ISSUE THREAD

**Issue by ajthinking** [spatie/laravel-collection-macros#167]
I found myself doing a project where a collection item needs to interact with the other items in various ways. So was thinking about a concept of access to the *remaining items* while iterating over a collection. Not sure if this is interesting to the repo, or if it already exists. If you think so Ill be happy to submit a PR with the example below and a few others.

### Example

    $students = collect([
        new Student('Anna'),
        new Student('Jeff'),
        new Student('Sarah'),
        new Student('George'),
    ]);

    $students->mapWithRemaining(function($student, $otherStudents) {
        $student->classMates = $otherStudents;
        return $student;
    });

### Code

    Collection::macro('mapWithRemaining', function ($callback) {
        $keys = array_keys($this->items);
        $items = array_map(function($item, $key) use($callback) {
            $remaining = $this->items;
            unset($remaining[$key]);
            return $callback($item, collect($remaining));
        }, $this->items, $keys);

        return new static(array_combine($keys, $items));
    });

**Comment by freekmurze** [comment]
Thank your for this. We currently don't have a need for this functionality, so we are going to pass.
