### ISSUE TITLE
pagination issue with groupBy

### ISSUE THREAD

**Issue by netstreet** [spatie/laravel-collection-macros#172]
How i can use pagination with groupBy?
now pagination count only groupBy keys and my solutions that is two because i groupBy my rows by status.

**Comment by alinmiron** [comment]
hi, 
This is a know problem in Laravel:

>  Currently, pagination operations that use a groupBy statement cannot be executed efficiently by Laravel. If you need to use a groupBy with a paginated result set, it is recommended that you query the database and create a paginator manually.

https://laravel.com/docs/6.x/pagination
