### ISSUE TITLE
Make usable with tightenco/collect

### ISSUE THREAD

**Issue by holtkamp** [spatie/laravel-collection-macros#18]
Thumbs up for this repo! Would like to share a challenge though when trying to combine it with [`tightenco/collect`](https://github.com/tightenco/collect) because of [the advice to not pull in the complete `illuminate/support` package](http://mattallan.org/2016/dont-use-illuminate-support/).

Context:
- was happily using `"tightenco/collect": "^5.3"` in my `composer.json`
- thought [these macro's](https://github.com/spatie/laravel-collection-macros) would be nice to have
- added `"spatie/laravel-collection-macros": "@stable"` to my `composer.json`
  - `"spatie/laravel-collection-macros"` [depends on `"illuminate/support"`](https://github.com/spatie/laravel-collection-macros/blob/cccf84ef74b98554b3638ef8b336aaef1b66e47c/composer.json#L26) 
  - `"illuminate/support"` `5.2.x` gets installed (which obviously differs from 5.3)

I concluded that I can not use both:
- https://github.com/tightenco/collect
- https://github.com/spatie/laravel-collection-macros

Does anyone have a suggestions on an approach which **does** allow me to install the macro's and does **not** depend on the complete `"illuminate/support"` package?

**Comment by sebastiandedeyne** [comment]
I don't think there's any nice possibility to get this working. Gonna close this for now unless something new comes up.
