### ISSUE TITLE
The Second Third etc macros are not working with custom keys

### ISSUE THREAD

**Issue by basepack** [spatie/laravel-collection-macros#181]
To reproduce:

```
$collection = collect()
$collection->put('array-key1', ['data']);
$collection->put('array-key2', ['data']);
$collection->put('array-key3', ['data']);
```

Calling `$collection->second()` will give `null` because it tries to get a key named `1` which does not exist.

To fix this, we need the following in for example the `Second` macro:
```
return $this->skip(1)->first();
```

This solution does not depend on the actual value of the array key.

**Comment by basepack** [comment]
Excuse for the PR spam, couldn't merge them in the browser...

**Comment by freekmurze** [comment]
We'll handle this in the relevant PRs.
