### ISSUE TITLE
Separate from Laravel?

### ISSUE THREAD

**Issue by holtkamp** [spatie/laravel-collection-macros#19]
Based on [this advice](http://mattallan.org/2016/dont-use-illuminate-support/) and [this attempt to separate it from ```illuminate/support```](https://github.com/tightenco/collect), it might be an idea to also isolate the macro's from the Laravel-specific parts?

An approach might be using two repositories:

- ```spatie/collection-macros``` with the bare macros.php file
- ```spatie/laravel-collection-macros```, which depends on ```spatie/collection-macros```

**off-topic**
Additionally, this might be usefull to adopt in the installation notes for non-Laravel users to automatically have the file```require```d by the Composer autoloader:

```json
  "autoload": {
    "files": [
      "vendor/spatie/laravel-collection-macros/src/macros.php"
    ]
  }
```

**Comment by freekmurze** [comment]
Hi, 

we are using Laravel for all our projects, so for us having to split this simple package up into two is just too much overhead.

You're of course free to fork our code, and split in into two packages in your own vendor namespace.

**Comment by holtkamp** [comment]
@freekmurze, ok, thanks for the response. 

>too much overhead

well... it is a one time action I would suppose? It seems non-Laravel use of Collections is gaining a lot of traction since [this book](https://adamwathan.me/refactoring-to-collections/)... might be interesting to join this movement and give this repo some additional use 😄 . 

Nevertheless, already grateful you guys created it! Cheers!
