### ISSUE TITLE
Parse error after package

### ISSUE THREAD

**Issue by mperezsc** [spatie/laravel-collection-macros#192]
Hello,

I just added this package and all my tests started to fail. There is a parse error originated at a file from this package `vendor\spatie\laravel-collection-macros\src\CollectionMacroServiceProvider.php:13`

The error, specifically says : `ParseError: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ',' or ')'`

I am using PHP 7.4.9, and have also tried with 7.4.3.

During package installation through composer, I saw this messages: 
`composer require spatie/laravel-collection-macros
Using version ^7.0 for spatie/laravel-collection-macros
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
Installing spatie/laravel-collection-macros (7.0.2): Downloading (100%)
spatie/laravel-collection-macros suggests installing amphp/parallel-functions (Required when using the parallel*-macros.)
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating optimized autoload files
Illuminate\Foundation\ComposerScripts::postAutoloadDump
@php artisan package:discover --ansi
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: cyrildewit/eloquent-viewable
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: qcod/laravel-gamify
Discovered Package: spatie/laravel-collection-macros
Package manifest generated successfully.`

Which seems quite standard. Any hint how to make my tests pass again? It is really odd because the application seems to be working fine.

Thanks

**Comment by freekmurze** [comment]
You probably have not installed the right PHP version on the CLI.

**Comment by mperezsc** [comment]
Thanks freekmurze for your prompt response. I am using laragon and running the tests from VSCode console thanks to BetterPHPUnit extension. It is the first time I run into this problem. Do you have an approximation of the place I could check if the CLI of VSCode is using the right PHP version?
