### ISSUE TITLE
Property Equals feature

### ISSUE THREAD

**Issue by wskyjames** [spatie/laravel-collection-macros#21]
Loving the collection macro's and have a feature request i wanted to pose before making a PR. I find myself frequently using filter or groupBy to neatly filter values by property. 

```php
$collection->filter(function($item) {
    $item->property == 'value';
})
```

After using ramda libraries i found the propEq function to provide this in a single line. My proposal is to provide propEq as a macro:

```php
Collection::macro('propEq', function ($value, $column = 'id') {
    return Collection::make($this->items)->filter(function($item) use ($value, $column) {
        if(! property_exists($item, $column)) {
            return false;
        }

        return $item->{$column} == $value;
   });
});
```

This allows the for the user to filter by id as a default, or provide a property as a second argument:

```php
$collection->propEq(1);
// Returns any items in the collection where id = 1
             
$collected->propEq('james', 'name');
// Return any items where name equals james
```

Any thoughts would be appreciated before submitting a PR.

**Comment by sebastiandedeyne** [comment]
Hmm, I don't think this is worth adding as a macro here, since it's very similar to the existing `where` method.

https://laravel.com/docs/master/collections#method-where

**Comment by wskyjames** [comment]
Ahh, right you are! Early morning brain before coffee!
