### ISSUE TITLE
v2 ideas

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/laravel-collection-macros#24]
List of ideas for when we do a major version bump. Maybe for Laravel 5.5?

- [x] Rename `toAssoc` to `fromPairs` so it's consistent with lodash
- [x] Add a `toPairs` method
- [x] Remove `mapToAssoc` since Laravel has `mapWithKeys`. Our methods having a different name is a good thing since they behave differently (ours use tuples `['k', 'v']`, Laravel uses single element assocs `['k' => 'v']`)
- [x] Remove methods that have made it to core (currently `split` and `partition`)

**Comment by freekmurze** [comment]
All good, I'll prepare a new major version soon

**Comment by sebastiandedeyne** [comment]
- [ ] Allow `range` to be called with 1 argument, and use `0` as `low` (`->range(20)` would be equivalent to `->range(0, 20)`

**Comment by freekmurze** [comment]
Excellent idea

**Comment by freekmurze** [comment]
Done, made a `withSize` function instead of the `range` proposal.
