### ISSUE TITLE
2.0.0 release seems incomplete?

### ISSUE THREAD

**Issue by holtkamp** [spatie/laravel-collection-macros#32]
A ```composer update``` just pulled in https://github.com/spatie/laravel-collection-macros/releases/tag/2.0.0

When looking at the release notes, I expected some functions to be removed, but they are still in the source code?

-  ```split``` https://github.com/spatie/laravel-collection-macros/blob/2.0.0/src/macros.php#L104
- ```partition``` https://github.com/spatie/laravel-collection-macros/blob/2.0.0/src/macros.php#L249
- ```mapToAssoc``` https://github.com/spatie/laravel-collection-macros/blob/2.0.0/src/macros.php#L208

Not sure what goes wrong here... The ZIP files provided in https://github.com/spatie/laravel-collection-macros/releases/tag/2.0.0 also still contain these macros...

**Comment by freekmurze** [comment]
Thanks for bringing this to my attention.

Release `2.0.0` was wrongly tagged. I've added this in the changelog. 

I've just tagged version `2.0.1` which contains the correct code.
