### ISSUE TITLE
Some todo's for creating the next major version targetting L5.5

### ISSUE THREAD

**Issue by freekmurze** [spatie/laravel-collection-macros#45]
- `dd` and `dump` have been added to Laravel itself, these macros may be removed.

**Comment by vladyslavstartsev** [comment]
I would like to have `paginate` and `simplePaginate` macros so you can paginate collection, at least I've used one. I can even make PR if you want to.

**Comment by sebastiandedeyne** [comment]
Those would be cool, I actually needed that the other day 😄 Wouldn't mind them in 5.4 already.

**Comment by freekmurze** [comment]
@vladyslavstartsev Those methods seem interested. Feel free to PR these methods to the current `master` branch. Be sure to included tests to prove that your code works. 👍

**Comment by mdrost** [comment]
What would you say about breaking backward compatibility in `sectionBy` https://github.com/spatie/laravel-collection-macros/pull/54#issuecomment-320124803 ?

**Comment by freekmurze** [comment]
In the `laravel-55` branch anything goes cc @AlexVanderbist

**Comment by sebastiandedeyne** [comment]
`laravel-55` branch is stable. Next week I'm gonna try the give the readme a makeover and we should be good to go!

**Comment by sebastiandedeyne** [comment]
I think we're ready 💪 

Gonna close this!

**Comment by freekmurze** [comment]
👏

**Comment by mdrost** [comment]
I'd just like to interject for a moment. `Collection` methods never returns nested collections but arrays. So shouldn't some macros like `sectionBy` also return nested arrays instead of collections (in `$itemsKey`)?

**Comment by vladyslavstartsev** [comment]
@mdrost I think it does, look at `groupBy`  and `chunk` methods
