### ISSUE TITLE
Library name

### ISSUE THREAD

**Issue by mdrost** [spatie/laravel-collection-macros#56]
Trying to answer this [question](https://laracasts.com/discuss/channels/laravel/laravel-vs-illuminate) I would like to know why this library is named `laravel-collection-macros` instead of `illuminate-collection-macros` while strictly Laravel is not a dependency?

**Comment by sebastiandedeyne** [comment]
Collection are more commonly refered too as "Laravel collections".

- "Import Laravel's collections" https://github.com/tightenco/collect
- "Laravel collections unraveled" https://leanpub.com/laravelcollectionsunraveled

Also, all our Laravel packages are prefixed with `laravel-`, so it's more consistent.
