### ISSUE TITLE
Remove range in next major version

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/laravel-collection-macros#84]
The base `Collection` class has a `times` static method, imo this one is too similar to keep maintaining it.

**Comment by sebastiandedeyne** [comment]
Why close? 😢

**Comment by freekmurze** [comment]
When tagging an issue with "next major release" I always close it not to clutter real issues that need attention. When creating a new major versions I revisit the tagged issues. When the needed work is done, I remove the tag.

**Comment by freekmurze** [comment]
`range` has been removed.
